@startuml
title Remove Book

actor Client
participant CatalogDao
participant CatalogItemVersions
participant removeBookFromCatalog
participant RemoveBookFromCatalogActivity
participant RemoveBookFromCatalogResponse

alt if book is removed or not
CatalogDao -> CatalogItemVersions : Inactive Status : False
CatalogItemVersions -> removeBookFromCatalog
Client <-- RemoveBookFromCatalogResponse
removeBookFromCatalog -> RemoveBookFromCatalogActivity : execute(RemoveBookFromCatalogRequest)
else otherwise, BookIdNotFound
CatalogDao -> CatalogItemVersions : Inactive Status : True
Client <-- CatalogItemVersions : BookNotFoundException
end



@enduml
